# Generated by Django 6.0.3 on 2026-05-22 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the local meetup or event.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A detailed description of what will happen at the meetup.')),
                ('location', models.CharField(help_text='The physical venue or address where the event will take place.', max_length=255)),
                ('date', models.DateTimeField(help_text='The scheduled date and time for this event.')),
                ('organizer', models.ForeignKey(help_text='The host or creator of the event.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The exact time when this RSVP was submitted.')),
                ('event', models.ForeignKey(help_text='The event the user is attending.', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(help_text='The user who is RSVPing to the event.', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
